export const TODOS = {
  ADD_TODO: "ADD_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  UNCOMPLETED_TODO: "UNCOMPLETED_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  ADD_FILTER: "ADD_FILTER",
  CLEAR_COMPLETED: "CLEAR_COMPLETED"
};
